Update package.json
asyncLiz/rollup-plugin-minify-html-literals pull request #17
Opened 2021-02-11 01:42 UTC by taylor-vann

Update devdependencies.
Fix tests after update.

2021-02-12 18:21 UTC, asyncLiz requested changes

2021-02-12 18:21 UTC, asyncLiz commented on package.json
> +    "rollup": "^2.38.5"
Any reason this can't support all three versions? `^0.65.2 || ^1.0.0 || ^2.0.0`

2021-02-12 18:21 UTC, asyncLiz commented on package.json
> +    "@types/mocha": "8.2.0",
Why do the devDependencies need to update? I get the peerDependencies would cause a problem if another project is using rollup v2

2021-02-12 18:21 UTC, asyncLiz commented on test/plugin.spec.ts
> +    expect(options.filter.calledWith()).to.be.true;
What's this change for?

2021-02-12 18:21 UTC, asyncLiz commented on CHANGELOG.md
> -
Can you revert this file? The changelog is automatically generated

2021-02-12 18:34 UTC, taylor-vann commented on package.json
> +    "rollup": "^2.38.5"
Was more concerned that maybe we don't want rely on old versions of rollup? nbd though

2021-02-12 18:37 UTC, taylor-vann commented on test/plugin.spec.ts
> +    expect(options.filter.calledWith()).to.be.true;
Updated syntax for the updated mocha / sinon (won't change if we don't upgrade devDependencies). The filename is implied from the statement:

`plugin.transofrm.apply(context, ['return', filename]`

2021-02-12 18:37 UTC, asyncLiz commented on package.json
> +    "rollup": "^2.38.5"
The peer dependency is not what the package relies on, but what it supports for different projects. Removing support for older versions of rollup would be a breaking change.

I don't see any code changes necessary in the actual plugin itself, which makes me thing that the API change from rollup v1 to v2 for this plugin was not breaking.

2021-02-12 18:40 UTC, taylor-vann commented on package.json
> +    "@types/mocha": "8.2.0",
Sometimes updating supporting libraries helps prevent staleness and big breaks in the future :) Can revert though if need be.

2021-02-12 18:40 UTC, taylor-vann commented on CHANGELOG.md
> -
sure thing!

2021-02-12 18:51 UTC, taylor-vann commented on package.json
> +    "rollup": "^2.38.5"
True true, I understand :) There were no API changes in rollup that were affected here between these versions. I can change it to `^0.65.2 || ^1.0.0 || ^2.0.0`.

The decision to go with 2.0.0? In the future, if there is an API change and we upgrade this library, we'll have to support multiple APIs or pick one. We can break now or potentially break later. If users need to use `0.65.2` or `^1.0.0` their dependencies can target an older version of this puglin I'm fine with either one.

My excuse aside, i'll change it to whatever you want :)

2021-02-12 19:30 UTC, taylor-vann commented on package.json
> +    "rollup": "^2.38.5"
Did a little research, wanted to see what other libraries are doing

the majority of rollup plugins on the rollup plugins git page follow two patterns for peerDependencies:
`"^1.20.0||^2.0.0"` [here](https://github.com/rollup/plugins/blob/master/packages/babel/package.json#L51)
`"^2.0.0"` [here](https://github.com/rollup/plugins/blob/master/packages/typescript/package.json#L48)

just wanted to confirm you want to include `^0.65.2` to avoid a breaking change :)

2021-02-12 19:44 UTC, asyncLiz commented on package.json
> +    "rollup": "^2.38.5"
While I don't mind making breaking changes, if there's literally no reason for it I don't see why we should force users to upgrade until it's necessary.

If they have an old project and don't want to update their build system, I don't see a reason to force them to. So let's keep all three versions.

2021-02-12 19:45 UTC, asyncLiz commented on package.json
> +    "@types/mocha": "8.2.0",
Let's revert for now, fewer things to keep track of and do right now. Usually when I update dev dependencies I'll do it for the trio of the three projects (the rollup plugin, minify-html-literals, and parse-literals) so that they're all in sync.

2021-02-12 22:20 UTC, taylor-vann commented on test/plugin.spec.ts
> +    expect(options.filter.calledWith()).to.be.true;
reverted in next commit

2021-02-12 22:20 UTC, taylor-vann commented on package.json
> +    "@types/mocha": "8.2.0",
reverted

2021-02-12 22:20 UTC, taylor-vann commented on package.json
> +    "rollup": "^2.38.5"
reverted

2021-02-12 23:48 UTC, taylor-vann reviewed
reverted all this :)

2021-02-18 22:32 UTC, taylor-vann commented
closing for a more simple PR.

2021-02-18 22:32 UTC, closed without merging